//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Curdoperation1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public int ID { get; set; }
       
        [Required(ErrorMessage = " Please enter Name")]
        
        public string NAME { get; set; }
        [Required(ErrorMessage = " Please enter Gender")]
      
        public string GENDER { get; set; }
        [Required(ErrorMessage = "Please enter Phone no")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
                   ErrorMessage = "Entered phone format is not valid.")]
        public string PHONE_NO { get; set; }
    }
   

}
